name: Daily README Update

on:
  schedule:
    - cron: '50 7 * * *'  # 08:10 Cameroon time (UTC+1)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}    # <-- important for write access!

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI README agent
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Your PAT token here
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REPO_NAME: ${{ github.repository }}
          BRANCH: main
        run: python main.py
