name: Daily README Update

on:
  schedule:
    - cron: '26 8 * * *'  # 08:13 UTC (09:13 Cameroon time UTC+1)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}    # Important for write access!

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug PAT token presence
        run: |
          echo "PAT_TOKEN is set: ${{ secrets.PAT_TOKEN != '' }}"
          echo "Length of PAT_TOKEN: ${{ secrets.PAT_TOKEN && secrets.PAT_TOKEN.length }}"

      - name: Run AI README agent
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REPO_NAME: ${{ github.repository }}
          BRANCH: main

          # ✅ Email environment variables
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

        run: python main.py
