name: Daily README Update

on:
  schedule:
    - cron: '02 8 * * *'  # 08:10 Cameroon time (UTC+1)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}    # <-- important for write access!

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug PAT token presence
        run: |
          echo "PAT_TOKEN is set: ${{ secrets.PAT_TOKEN != '' }}"
          echo "Length of PAT_TOKEN: ${{ secrets.PAT_TOKEN && secrets.PAT_TOKEN.length }}"

      - name: Run AI README agent
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}     # Pass PAT_TOKEN here, matches Python code
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REPO_NAME: ${{ github.repository }}
          BRANCH: main
        run: python main.py
